services:
  bkt-service:
    build:
      context: .
      dockerfile: Dockerfile.bkt
    ports:
      - "8001:8080"
    env_file:
      - .env
    environment:
      - GCS_CHECKPOINT_URI=${GCS_CHECKPOINT_URI}
